
image:
  file: .gitpod.Dockerfile
ports:
    - port: 5500
      onOpen: open-preview
      visibility: public
    - port: 3306
      onOpen: ignore
      visibility: public
tasks:
    - init: |
        cp .env.example .env &&
        pipenv install  &&
        mysql -u root -e "CREATE DATABASE buzzr" &&
        pipenv run init &&
        pipenv run migrate &&
        pipenv run upgrade;
      command: >
        pipenv run start;
    - command: python3 welcome.py
      openMode: split-right

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    main: false

vscode:
  extensions:
    - rangav.vscode-thunder-client